# Generated by Django 5.1.3 on 2024-11-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatecrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realestate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('property_type', models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('land', 'land')], default='land', max_length=200)),
                ('number_of_bedroom', models.PositiveIntegerField()),
                ('square_footage', models.PositiveIntegerField()),
                ('location', models.CharField(choices=[('city', 'city'), ('neighbourhood', 'neighbourhood')], default='city', max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='realestate_images')),
                ('contact', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
